apiVersion: v1
kind: Pod
metadata:
  name: gpu
  namespace: test
spec:
  runtimeClassName: nvidia
  nodeSelector:
    gpu: nvidia
  # tolerations:
  # - key: "node-role.kubernetes.io/control-plane"
  #   operator: "Exists"
  #   effect: "NoSchedule"
  containers:
  - name: cuda-container
    # image: nvcr.io/nvidia/cuda:12.6.0-base-ubuntu20.04
    image: pytorch/pytorch:2.4.1-cuda11.8-cudnn9-runtime
    # image: docker.io/nvidia/cuda:11.0.3-base-ubuntu20.04
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sleep"
    - "3650d"
    resources:
      limits:
        cpu: "2"
        memory: "6Gi"
        nvidia.com/gpu: "1"
  #   volumeMounts:
  #     - name: smb
  #       mountPath: "/data"
  #       readOnly: false
  # volumes:
  #   - name: smb
  #     persistentVolumeClaim:
  #       claimName: pvc-smb