apiVersion: v1
kind: Namespace
metadata:
  name: ghost
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost-config
  namespace: ghost
data:
  config.production.json: |
    {
      "url": "http://localhost:2368",
      "server": {
        "port": 2368,
        "host": "::"
      },
      "mail": {
        "transport": "Direct"
      },
      "logging": {
        "transports": [
          "file",
          "stdout"
        ]
      },
      "process": "systemd",
      "paths": {
        "contentPath": "/var/lib/ghost/content"
      },
      "security": {
        "staffDeviceVerification": false
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  namespace: ghost
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi