apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-code-pv
  namespace: code-server
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.12
    path: /home/nfs_server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content-pvc
  namespace: code-server
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi