apiVersion: v1
kind: Namespace
metadata:
  name: nfs-server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: nfs-server
spec:
  capacity:
    storage: 980Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # 필요에 따라 `Recycle` 또는 `Delete`로 변경 가능
  storageClassName: ""
  local:
    path: /var/lib/nfs-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - talos-6in-aky  # 특정 노드 지정
  claimRef:                  # PVC를 미리 지정(바인딩·이름공간 고정)
    namespace: nfs-server
    name: nfs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: nfs-server
spec:
  volumeName: nfs-pv         # 위 PV에 직접 바인딩
  storageClassName: ""       # PV와 맞춰서 비워 둡니다
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 980Gi