apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-data-azsmb
  namespace: nfs-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: az-smb
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-backup
  namespace: nfs-server
spec:
  schedule: "0 2 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: rsync
            image: alpine:3.19
            command: ["sh","-c",
              "apk add --no-cache rsync && \
               rsync -a --delete --no-links /data/ /backup/app-data"]
            volumeMounts:
            - name: nfs-src
              mountPath: /data
            - name: smb-dest
              mountPath: /backup
          volumes:
          - name: nfs-src
            persistentVolumeClaim:
            nfs:
              server: 192.168.0.244
              path: /pod-data
              readOnly: true
          - name: smb-dest
            persistentVolumeClaim:
              claimName: pod-data-azsmb