apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
provisioner: smb.csi.k8s.io
parameters:
  source: //192.168.4.4/azdata
  csi.storage.k8s.io/node-stage-secret-name: smb-creds
  csi.storage.k8s.io/node-stage-secret-namespace: csi-smb-provisioner
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=3.0
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: false