apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-smb
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "smb"
  resources:
    requests:
      storage: 10Gi